# file: scripts/plot_curves_clean.py
"""Clean training curves: DQN vs PPO with timestep-aligned mean±std shading.

Key improvements over the original plot_curves.py:
- Aligns seeds by timestep (union of all observed timesteps), not by truncation.
- Missing values are NaN, not 0 — mean/std use skipna=True.
- Shading is drawn only when n_valid_seeds >= 2 at a given timestep.
- No single-seed faint traces — only mean lines and ±std bands.
"""

import os, sys
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

COLORS = {"dqn": "#1F4E79", "ppo": "#C0392B"}
SEEDS = [42, 123, 456, 789, 1024]
REWARDS = ["aggressive", "baseline", "balanced", "comfort", "conservative"]

# ---------------------------------------------------------------------------
# Data loading — timestep-aligned
# ---------------------------------------------------------------------------

def load_aligned_curves(log_dir: str, algo: str, reward_cfg: str):
    """Return (common_ts: np.ndarray, rwd_df: pd.DataFrame, n_valid: np.ndarray).

    rwd_df has shape (n_seeds, n_timesteps).  Missing timesteps are NaN.
    n_valid[t] = number of seeds that have data at timestep t.
    """
    seed_data = {}  # seed -> pd.Series (index=timestep)
    for s in SEEDS:
        cp = os.path.join(log_dir, algo, reward_cfg, f"seed_{s}", "eval_metrics.csv")
        if not os.path.exists(cp):
            continue
        try:
            df = pd.read_csv(cp)
        except Exception:
            continue
        if "timestep" not in df.columns or "mean_reward" not in df.columns:
            continue
        # Keep only timestep and mean_reward, drop duplicates on timestep
        df = df[["timestep", "mean_reward"]].drop_duplicates(subset="timestep")
        df = df.set_index("timestep")["mean_reward"]
        seed_data[s] = df

    if not seed_data:
        return None, None, None

    # Union of all timesteps across seeds
    all_ts = sorted(set().union(*(s.index for s in seed_data.values())))
    common_ts = np.array(all_ts, dtype=float)

    # Build aligned matrix
    n_seeds = len(SEEDS)
    rwd_matrix = np.full((n_seeds, len(common_ts)), np.nan)
    seed_indices = {s: i for i, s in enumerate(SEEDS)}

    for s, series in seed_data.items():
        idx = seed_indices[s]
        for t, val in series.items():
            j = all_ts.index(t)
            rwd_matrix[idx, j] = val

    n_valid = np.sum(~np.isnan(rwd_matrix), axis=0)

    return common_ts, rwd_matrix, n_valid


def compute_stats(rwd_matrix: np.ndarray, n_valid: np.ndarray):
    """Return (mean, std) with skipna=True; std is NaN where n_valid < 2."""
    mean = np.nanmean(rwd_matrix, axis=0)
    std = np.nanstd(rwd_matrix, axis=0)
    # Mask std where fewer than 2 seeds present
    std = np.where(n_valid >= 2, std, np.nan)
    return mean, std


# ---------------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------------

def plot_one_reward(log_dir: str, reward_cfg: str, out_path: str):
    """Generate a single clean training-curve figure."""
    fig, ax = plt.subplots(figsize=(8, 5))

    for algo in ["dqn", "ppo"]:
        ts, rwd_matrix, n_valid = load_aligned_curves(log_dir, algo, reward_cfg)
        if ts is None:
            print(f"  [WARNING] No data for {algo}/{reward_cfg}")
            continue

        mean, std = compute_stats(rwd_matrix, n_valid)
        c = COLORS[algo]

        # Mean line
        ax.plot(ts, mean, color=c, linewidth=2, label=f"{algo.upper()}")

        # ±std shading (only where n_valid >= 2)
        valid_mask = n_valid >= 2
        if valid_mask.sum() > 1:
            # Split into contiguous segments so shading doesn't bridge gaps
            ts_valid = ts[valid_mask]
            mu_valid = mean[valid_mask]
            sd_valid = std[valid_mask]
            ax.fill_between(ts_valid, mu_valid - sd_valid, mu_valid + sd_valid,
                            color=c, alpha=0.15, linewidth=0)

    ax.set_xlabel("Timesteps", fontsize=11)
    ax.set_ylabel("Episode Reward", fontsize=11)
    ax.set_title(f"Training Curves: DQN vs PPO ({reward_cfg} reward)", fontsize=13)
    ax.legend(fontsize=10)
    ax.grid(True, alpha=0.25)
    fig.tight_layout()
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    fig.savefig(out_path, dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {out_path}")


def generate_check_report(log_dir: str, out_path: str):
    """Generate a detailed check report for all training curves."""
    lines = []
    lines.append("# Training Curves Clean Check Report")
    lines.append("")
    lines.append(f"Generated by: scripts/plot_curves_clean.py")
    lines.append("")

    for reward_cfg in REWARDS:
        lines.append(f"## {reward_cfg}")
        lines.append("")

        for algo in ["dqn", "ppo"]:
            ts, rwd_matrix, n_valid = load_aligned_curves(log_dir, algo, reward_cfg)
            if ts is None:
                lines.append(f"- **{algo.upper()}**: NO DATA")
                lines.append("")
                continue

            # Which seeds were found
            found_seeds = []
            for i, s in enumerate(SEEDS):
                if not np.all(np.isnan(rwd_matrix[i])):
                    n_pts = int(np.sum(~np.isnan(rwd_matrix[i])))
                    found_seeds.append(f"seed_{s} ({n_pts} points)")

            lines.append(f"### {algo.upper()}")
            lines.append(f"- Seeds found: {', '.join(found_seeds)}")
            lines.append(f"- Total timesteps in union grid: {len(ts)}")
            lines.append(f"- Timestep range: [{int(ts[0])}, {int(ts[-1])}]")

            # Per-timestep n_valid
            low_n = [(int(ts[i]), int(n_valid[i])) for i in range(len(ts)) if n_valid[i] < 5]
            if low_n:
                lines.append(f"- Timesteps with <5 seeds: {low_n}")
            n_lt_2 = [(int(ts[i]), int(n_valid[i])) for i in range(len(ts)) if n_valid[i] < 2]
            if n_lt_2:
                lines.append(f"- **Timesteps with <2 seeds (no shading):** {n_lt_2}")
            else:
                lines.append(f"- All timesteps have ≥2 seeds (shading drawn everywhere)")

            # Early termination
            early_seeds = []
            for i, s in enumerate(SEEDS):
                n_pts = int(np.sum(~np.isnan(rwd_matrix[i])))
                if n_pts < len(ts):
                    last_ts_idx = np.where(~np.isnan(rwd_matrix[i]))[0][-1]
                    early_seeds.append(f"seed_{s} ends at t={int(ts[last_ts_idx])} ({n_pts}/{len(ts)} points)")
            if early_seeds:
                lines.append(f"- Early termination: {'; '.join(early_seeds)}")

            lines.append("")

        # Recommendation
        lines.append(f"**Recommendation for '{reward_cfg}'**: ",)
        if reward_cfg in ("aggressive", "baseline"):
            lines.append("suitable for main text.")
        else:
            lines.append("keep in figures_clean/ for reference; not primary for main text.")
        lines.append("")

    # Write
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Check report saved: {out_path}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    log_dir = os.path.join(ROOT, "logs")
    out_dir = os.path.join(ROOT, "figures_clean")

    # Generate clean training curves
    for reward_cfg in REWARDS:
        print(f"Processing: {reward_cfg}")
        out_path = os.path.join(out_dir, f"training_curves_{reward_cfg}_clean.png")
        plot_one_reward(log_dir, reward_cfg, out_path)

    # Generate check report
    report_path = os.path.join(ROOT, "run_logs", "training_curves_clean_check.md")
    generate_check_report(log_dir, report_path)

    print("\nAll clean training curves generated.")


if __name__ == "__main__":
    main()
